version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-networks
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-networks

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    networks:
      - app-networks

volumes:
  mongo_data:

networks:
  app-networks:
    driver: bridge
